<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="1.65.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OpenAC.Net.DFe.Core\OpenAC.Net.DFe.Core.csproj" />
        <ProjectReference Include="..\OpenAC.Net.DFe.Generator\OpenAC.Net.DFe.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="true" />
    </ItemGroup>

    <ItemGroup>
        <None Update="cdata_teste.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
