using System.Collections.Generic;
using System.Linq;
using System.Text;
using OpenAC.Net.DFe.Generator.Models;

namespace OpenAC.Net.DFe.Generator.Emitter;

/// <summary>
/// Emissor de código C# que gera o código-fonte dos métodos parciais de serialização e deserialização XML para classes DFe.
/// </summary>
public static class DFeSerializerEmitter
{
    /// <summary>
    /// Gera a string de código-fonte C# da classe parcial implementando a serialização e deserialização XML para o modelo informado.
    /// </summary>
    /// <param name="model">Modelo de metadados da classe DFe.</param>
    /// <returns>Código-fonte em C# pronto para compilação.</returns>
    public static string Generate(DFeClassModel model)
    {
        var sb = new StringBuilder();
        var genericSig = model.GenericTypeSignature;
        var genericConstraints = model.GenericTypeConstraintsClause;

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591, CS8600, CS8601, CS8602, CS8603, CS8604");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Xml.Linq;");
        sb.AppendLine("using OpenAC.Net.Core.Extensions;");
        sb.AppendLine("using OpenAC.Net.DFe.Core.Extensions;");
        sb.AppendLine("using OpenAC.Net.DFe.Core.Serializer;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        var classDecl = $"    partial class {model.ClassName}{genericSig} {genericConstraints}";
        sb.AppendLine(classDecl);
        sb.AppendLine("    {");

        if (model.IsCollectionClass && model.CollectionItemType != null)
        {
            EmitCollectionClassMethods(sb, model);
        }
        else
        {
            EmitClassMethods(sb, model);
        }

        EmitEnumHelpers(sb, model);

        sb.AppendLine("    }");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitCollectionClassMethods(StringBuilder sb, DFeClassModel model)
    {
        var defaultRootTag = model.RootTag ?? model.ClassName;
        var defaultNs = model.RootNamespace ?? string.Empty;
        var overrideMod = model.IsDFeDocument ? "override " : "";

        // WriteToXml
        sb.AppendLine($"        public {overrideMod}XElement WriteToXml(string? rootName = null, string? rootNamespace = null, SerializerOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            options ??= new SerializerOptions();");
        sb.AppendLine($"            var name = string.IsNullOrEmpty(rootName) ? \"{defaultRootTag}\" : rootName!;");
        sb.AppendLine($"            var ns = rootNamespace ?? \"{defaultNs}\";");
        sb.AppendLine("            XNamespace aw = ns;");
        sb.AppendLine("            var element = string.IsNullOrEmpty(ns) ? new XElement(name) : new XElement(aw + name);");
        sb.AppendLine("            foreach (var colItem in this)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (colItem != null)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var childElem = colItem.WriteToXml(null, null, options);");
        sb.AppendLine("                    element.Add(childElem);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            return element;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ReadFromXml Static Factory
        sb.AppendLine($"        public static global::{model.TypeFullName}? ReadFromXml(XElement? element, SerializerOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (element == null) return null;");
        sb.AppendLine("            options ??= new SerializerOptions();");
        sb.AppendLine($"            var item = new global::{model.TypeFullName}();");
        sb.AppendLine("            item.ReadXml(element, options);");
        sb.AppendLine("            return item;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ReadXml Instance Method
        sb.AppendLine($"        public {overrideMod}void ReadXml(XElement element, SerializerOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (element == null) return;");
        sb.AppendLine("            options ??= new SerializerOptions();");
        sb.AppendLine("            this.Clear();");
        sb.AppendLine("            foreach (var childNode in element.Elements())");
        sb.AppendLine("            {");
        sb.AppendLine($"                var child = global::{model.CollectionItemType}.ReadFromXml(childNode, options);");
        sb.AppendLine("                if (child != null) this.Add(child);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitClassMethods(StringBuilder sb, DFeClassModel model)
    {
        var defaultRootTag = model.RootTag ?? model.ClassName;
        var defaultNs = model.RootNamespace ?? string.Empty;
        var overrideMod = model.IsDFeDocument ? "override " : "";

        // WriteToXml
        sb.AppendLine($"        public {overrideMod}XElement WriteToXml(string? rootName = null, string? rootNamespace = null, SerializerOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            options ??= new SerializerOptions();");
        sb.AppendLine($"            var name = string.IsNullOrEmpty(rootName) ? \"{defaultRootTag}\" : rootName!;");
        sb.AppendLine($"            var ns = rootNamespace ?? \"{defaultNs}\";");
        sb.AppendLine("            XNamespace aw = ns;");
        sb.AppendLine("            var element = string.IsNullOrEmpty(ns) ? new XElement(name) : new XElement(aw + name);");
        sb.AppendLine();

        // If it's a ValueElement class
        if (model.IsValueElement && model.ValueElementProperty != null)
        {
            var valProp = model.ValueElementProperty;
            sb.AppendLine($"            var valStr = DFeSerializerHelper.FormatValue_{valProp.TipoCampo}(this.{valProp.Name}, {valProp.Min}, options);");
            sb.AppendLine("            element.Value = valStr ?? string.Empty;");
            sb.AppendLine();
        }

        // Emit properties serialization
        foreach (var prop in model.Properties)
        {
            if (model.IsValueElement && prop.PropertyKind == DFePropertyKind.ItemValue)
                continue;

            EmitPropertySerialize(sb, prop);
        }

        sb.AppendLine("            return element;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ReadFromXml Static Factory
        sb.AppendLine($"        public static global::{model.TypeFullName}? ReadFromXml(XElement? element, SerializerOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (element == null) return null;");
        sb.AppendLine("            options ??= new SerializerOptions();");
        sb.AppendLine($"            var item = new global::{model.TypeFullName}();");
        sb.AppendLine("            item.ReadXml(element, options);");
        sb.AppendLine("            return item;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ReadXml Instance Method
        sb.AppendLine($"        public {overrideMod}void ReadXml(XElement element, SerializerOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (element == null) return;");
        sb.AppendLine("            options ??= new SerializerOptions();");
        sb.AppendLine();

        // ValueElement property reading
        if (model.IsValueElement && model.ValueElementProperty != null)
        {
            var valProp = model.ValueElementProperty;
            sb.AppendLine($"            this.{valProp.Name} = {GetParseCall(valProp, "element.Value")};");
        }

        // Attributes reading
        foreach (var prop in model.Properties.Where(p => p.PropertyKind == DFePropertyKind.Attribute))
        {
            sb.AppendLine($"            var attr_{prop.Name} = element.Attribute(\"{prop.TagName}\");");
            sb.AppendLine($"            if (attr_{prop.Name} != null && !string.IsNullOrEmpty(attr_{prop.Name}.Value))");
            sb.AppendLine("            {");
            var parseCall = GetParseCall(prop, $"attr_{prop.Name}.Value");
            sb.AppendLine($"                this.{prop.Name} = {parseCall};");
            sb.AppendLine("            }");
            if (prop.Ocorrencia != OcorrenciaModel.Obrigatoria)
            {
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                sb.AppendLine($"                this.{prop.Name} = default!;");
                sb.AppendLine("            }");
            }
        }

        // Elements, Collections, Dictionaries, Interfaces reading
        foreach (var prop in model.Properties.Where(p => p.PropertyKind != DFePropertyKind.Attribute && p.PropertyKind != DFePropertyKind.ItemValue))
        {
            sb.AppendLine();
            EmitPropertyDeserialize(sb, prop);
        }

        sb.AppendLine("        }");
    }

    private static void EmitPropertySerialize(StringBuilder sb, DFePropertyModel prop)
    {
        var indent = "            ";
        var hasCondition = prop.HasShouldSerialize;

        if (hasCondition)
        {
            sb.AppendLine($"{indent}if (this.ShouldSerialize{prop.Name}())");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        switch (prop.PropertyKind)
        {
            case DFePropertyKind.Attribute:
                EmitAttributeSerialize(sb, prop, indent);
                break;

            case DFePropertyKind.Element:
                EmitElementSerialize(sb, prop, indent);
                break;

            case DFePropertyKind.Collection:
                EmitCollectionSerialize(sb, prop, indent);
                break;

            case DFePropertyKind.Dictionary:
                EmitDictionarySerialize(sb, prop, indent);
                break;

            case DFePropertyKind.Interface:
                EmitInterfaceSerialize(sb, prop, indent);
                break;

            default:
                break;
        }

        if (hasCondition)
        {
            indent = "            ";
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void EmitAttributeSerialize(StringBuilder sb, DFePropertyModel prop, string indent)
    {
        var valExpr = $"this.{prop.Name}";

        if (prop.Ocorrencia == OcorrenciaModel.Obrigatoria)
        {
            var formatCall = GetFormatCall(prop, valExpr);
            sb.AppendLine($"{indent}var attrVal_{prop.Name} = {formatCall} ?? string.Empty;");
            sb.AppendLine($"{indent}element.Add(new XAttribute(\"{prop.TagName}\", attrVal_{prop.Name}));");
        }
        else if (prop.IsNullable || (prop.TypeKind == DFeTypeKind.Primitive && prop.TypeFullName == "string"))
        {
            sb.AppendLine($"{indent}if ({valExpr} != null)");
            sb.AppendLine($"{indent}{{");
            var inner = indent + "    ";
            EmitAttributeAdd(sb, prop, inner, valExpr);
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            EmitAttributeAdd(sb, prop, indent, valExpr);
        }
    }

    private static void EmitAttributeAdd(StringBuilder sb, DFePropertyModel prop, string indent, string valExpr)
    {
        var formatCall = GetFormatCall(prop, valExpr);
        sb.AppendLine($"{indent}var attrVal_{prop.Name} = {formatCall};");
        sb.AppendLine($"{indent}if (attrVal_{prop.Name} != null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    element.Add(new XAttribute(\"{prop.TagName}\", attrVal_{prop.Name}));");
        sb.AppendLine($"{indent}}}");
    }

    private static void EmitElementSerialize(StringBuilder sb, DFePropertyModel prop, string indent)
    {
        var valExpr = $"this.{prop.Name}";

        if (prop.TypeKind is DFeTypeKind.Class or DFeTypeKind.RootClass or DFeTypeKind.ValueElement)
        {
            sb.AppendLine($"{indent}if ({valExpr} != null)");
            sb.AppendLine($"{indent}{{");
            var inner = indent + "    ";
            var tagNs = prop.TagNamespace != null ? $"\"{prop.TagNamespace}\"" : "null";
            sb.AppendLine($"{inner}var childElem = {valExpr}.WriteToXml(\"{prop.TagName}\", {tagNs}, options);");
            sb.AppendLine($"{inner}element.Add(childElem);");
            sb.AppendLine($"{indent}}}");
            if (prop.Ocorrencia == OcorrenciaModel.Obrigatoria)
            {
                sb.AppendLine($"{indent}else");
                sb.AppendLine($"{indent}{{");
                var tagNsReq = string.IsNullOrEmpty(prop.TagNamespace) ? "aw" : $"(XNamespace)\"{prop.TagNamespace}\"";
                sb.AppendLine($"{indent}    element.Add(new XElement({tagNsReq} + \"{prop.TagName}\"));");
                sb.AppendLine($"{indent}}}");
            }
            return;
        }

        if (prop.Ocorrencia == OcorrenciaModel.MaiorQueZero)
        {
            sb.AppendLine($"{indent}if ({valExpr} > 0)");
            sb.AppendLine($"{indent}{{");
            var inner = indent + "    ";
            EmitSingleElementAdd(sb, prop, inner, valExpr);
            sb.AppendLine($"{indent}}}");
        }
        else if (prop.Ocorrencia == OcorrenciaModel.Obrigatoria)
        {
            var formatCall = GetFormatCall(prop, valExpr);
            sb.AppendLine($"{indent}var elemVal_{prop.Name} = {formatCall} ?? string.Empty;");
            var tagNs = string.IsNullOrEmpty(prop.TagNamespace) ? "aw" : $"(XNamespace)\"{prop.TagNamespace}\"";

            if (prop.UseCData)
            {
                sb.AppendLine($"{indent}element.Add(new XElement({tagNs} + \"{prop.TagName}\", new XCData(elemVal_{prop.Name})));");
            }
            else
            {
                sb.AppendLine($"{indent}element.Add(new XElement({tagNs} + \"{prop.TagName}\", elemVal_{prop.Name}));");
            }
        }
        else if (prop.IsNullable || prop.TypeFullName == "string")
        {
            sb.AppendLine($"{indent}if ({valExpr} != null)");
            sb.AppendLine($"{indent}{{");
            var inner = indent + "    ";
            EmitSingleElementAdd(sb, prop, inner, valExpr);
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            EmitSingleElementAdd(sb, prop, indent, valExpr);
        }
    }

    private static void EmitSingleElementAdd(StringBuilder sb, DFePropertyModel prop, string indent, string valExpr)
    {
        var formatCall = GetFormatCall(prop, valExpr);
        sb.AppendLine($"{indent}var elemVal_{prop.Name} = {formatCall};");
        sb.AppendLine($"{indent}if (elemVal_{prop.Name} != null)");
        sb.AppendLine($"{indent}{{");
        var tagNs = string.IsNullOrEmpty(prop.TagNamespace) ? "aw" : $"(XNamespace)\"{prop.TagNamespace}\"";

        if (prop.UseCData)
        {
            sb.AppendLine($"{indent}    element.Add(new XElement({tagNs} + \"{prop.TagName}\", new XCData(elemVal_{prop.Name})));");
        }
        else
        {
            sb.AppendLine($"{indent}    element.Add(new XElement({tagNs} + \"{prop.TagName}\", elemVal_{prop.Name}));");
        }
        sb.AppendLine($"{indent}}}");
    }

    private static void EmitCollectionSerialize(StringBuilder sb, DFePropertyModel prop, string indent)
    {
        var valExpr = $"this.{prop.Name}";
        sb.AppendLine($"{indent}if ({valExpr} != null)");
        sb.AppendLine($"{indent}{{");
        var inner = indent + "    ";

        var hasContainer = !string.IsNullOrEmpty(prop.CollectionContainerTagName) &&
                           (prop.ItemMappings.Length > 0 || prop.TagName != prop.CollectionContainerTagName);

        var targetContainer = "element";
        if (hasContainer)
        {
            var tagNs = string.IsNullOrEmpty(prop.TagNamespace) ? "aw" : $"(XNamespace)\"{prop.TagNamespace}\"";
            sb.AppendLine($"{inner}var colContainer_{prop.Name} = new XElement({tagNs} + \"{prop.CollectionContainerTagName}\");");
            targetContainer = $"colContainer_{prop.Name}";
        }

        sb.AppendLine($"{inner}foreach (var colItem in {valExpr})");
        sb.AppendLine($"{inner}{{");
        var loopIndent = inner + "    ";

        if (prop.ItemMappings.Length > 0)
        {
            for (int i = 0; i < prop.ItemMappings.Length; i++)
            {
                var map = prop.ItemMappings[i];
                var elsePrefix = i > 0 ? "else " : "";
                var itemNs = map.TagNamespace != null ? $"\"{map.TagNamespace}\"" : "null";

                if (map.IsCollection && map.CollectionItemType != null)
                {
                    sb.AppendLine($"{loopIndent}{elsePrefix}if (colItem is global::{map.TypeFullName} colItem_{i})");
                    sb.AppendLine($"{loopIndent}{{");
                    sb.AppendLine($"{loopIndent}    foreach (var subItem in colItem_{i})");
                    sb.AppendLine($"{loopIndent}    {{");
                    sb.AppendLine($"{loopIndent}        if (subItem != null)");
                    sb.AppendLine($"{loopIndent}        {{");
                    sb.AppendLine($"{loopIndent}            var childElem = subItem.WriteToXml(\"{map.TagName}\", {itemNs}, options);");
                    sb.AppendLine($"{loopIndent}            {targetContainer}.Add(childElem);");
                    sb.AppendLine($"{loopIndent}        }}");
                    sb.AppendLine($"{loopIndent}    }}");
                    sb.AppendLine($"{loopIndent}}}");
                }
                else
                {
                    sb.AppendLine($"{loopIndent}{elsePrefix}if (colItem is global::{map.TypeFullName} item_{i})");
                    sb.AppendLine($"{loopIndent}{{");
                    sb.AppendLine($"{loopIndent}    var childElem = item_{i}.WriteToXml(\"{map.TagName}\", {itemNs}, options);");
                    sb.AppendLine($"{loopIndent}    {targetContainer}.Add(childElem);");
                    sb.AppendLine($"{loopIndent}}}");
                }
            }
        }
        else if (prop.CollectionItemTypeKind is DFeTypeKind.Class or DFeTypeKind.RootClass or DFeTypeKind.ValueElement && prop.CollectionItemType != null)
        {
            sb.AppendLine($"{loopIndent}if (colItem != null)");
            sb.AppendLine($"{loopIndent}{{");
            var itemNs = prop.TagNamespace != null ? $"\"{prop.TagNamespace}\"" : "null";
            sb.AppendLine($"{loopIndent}    var childElem = colItem.WriteToXml(\"{prop.TagName}\", {itemNs}, options);");
            sb.AppendLine($"{loopIndent}    {targetContainer}.Add(childElem);");
            sb.AppendLine($"{loopIndent}}}");
        }
        else
        {
            // Primitive or Enum collection
            var itemFormatCall = GetFormatCall(prop, "colItem");
            sb.AppendLine($"{loopIndent}var itemStr = {itemFormatCall};");
            sb.AppendLine($"{loopIndent}if (itemStr != null)");
            sb.AppendLine($"{loopIndent}{{");
            var tagNs = string.IsNullOrEmpty(prop.TagNamespace) ? "aw" : $"(XNamespace)\"{prop.TagNamespace}\"";
            sb.AppendLine($"{loopIndent}    {targetContainer}.Add(new XElement({tagNs} + \"{prop.TagName}\", itemStr));");
            sb.AppendLine($"{loopIndent}}}");
        }

        sb.AppendLine($"{inner}}}");

        if (hasContainer)
        {
            sb.AppendLine($"{inner}element.Add({targetContainer});");
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void EmitDictionarySerialize(StringBuilder sb, DFePropertyModel prop, string indent)
    {
        var valExpr = $"this.{prop.Name}";
        sb.AppendLine($"{indent}if ({valExpr} != null)");
        sb.AppendLine($"{indent}{{");
        var inner = indent + "    ";
        var tagNs = string.IsNullOrEmpty(prop.TagNamespace) ? "aw" : $"(XNamespace)\"{prop.TagNamespace}\"";
        sb.AppendLine($"{inner}var dictElem_{prop.Name} = new XElement({tagNs} + \"{prop.TagName}\");");
        sb.AppendLine($"{inner}foreach (var kvp in {valExpr})");
        sb.AppendLine($"{inner}{{");
        var loopIndent = inner + "    ";

        var keyName = prop.DictionaryKey?.Name ?? "Key";
        var valName = prop.DictionaryValue?.Name ?? "Value";
        var keyAsAttr = prop.DictionaryKey?.AsAttribute ?? false;

        var keyTipo = prop.DictionaryKey?.Tipo ?? TipoCampoModel.Str;
        var valTipo = prop.DictionaryValue?.Tipo ?? TipoCampoModel.Str;

        var keyFormat = prop.EnumInfo != null
            ? $"FormatEnum_{GetSafeIdentifier(prop.EnumInfo.EnumFullName)}(kvp.Key)"
            : GetPrimitiveFormatCall(keyTipo, "kvp.Key", prop.DictionaryKey?.Min ?? 0);

        var valFormat = GetPrimitiveFormatCall(valTipo, "kvp.Value", prop.DictionaryValue?.Min ?? 0);

        sb.AppendLine($"{loopIndent}var keyStr = {keyFormat};");
        sb.AppendLine($"{loopIndent}var valStr = {valFormat};");

        if (keyAsAttr)
        {
            sb.AppendLine($"{loopIndent}var entryElem = new XElement(\"{valName}\", valStr);");
            sb.AppendLine($"{loopIndent}if (keyStr != null) entryElem.Add(new XAttribute(\"{keyName}\", keyStr));");
            sb.AppendLine($"{loopIndent}dictElem_{prop.Name}.Add(entryElem);");
        }
        else
        {
            sb.AppendLine($"{loopIndent}var entryElem = new XElement(\"Item\");");
            sb.AppendLine($"{loopIndent}if (keyStr != null) entryElem.Add(new XElement(\"{keyName}\", keyStr));");
            sb.AppendLine($"{loopIndent}if (valStr != null) entryElem.Add(new XElement(\"{valName}\", valStr));");
            sb.AppendLine($"{loopIndent}dictElem_{prop.Name}.Add(entryElem);");
        }

        sb.AppendLine($"{inner}}}");
        sb.AppendLine($"{inner}element.Add(dictElem_{prop.Name});");
        sb.AppendLine($"{indent}}}");
    }

    private static void EmitInterfaceSerialize(StringBuilder sb, DFePropertyModel prop, string indent)
    {
        var valExpr = $"this.{prop.Name}";
        sb.AppendLine($"{indent}if ({valExpr} != null)");
        sb.AppendLine($"{indent}{{");
        var inner = indent + "    ";

        for (int i = 0; i < prop.ItemMappings.Length; i++)
        {
            var map = prop.ItemMappings[i];
            var elsePrefix = i > 0 ? "else " : "";
            var itemNs = map.TagNamespace != null ? $"\"{map.TagNamespace}\"" : "null";

            if (map.IsCollection && map.CollectionItemType != null)
            {
                sb.AppendLine($"{inner}{elsePrefix}if ({valExpr} is global::{map.TypeFullName} colItem_{i})");
                sb.AppendLine($"{inner}{{");
                sb.AppendLine($"{inner}    foreach (var subItem in colItem_{i})");
                sb.AppendLine($"{inner}    {{");
                sb.AppendLine($"{inner}        if (subItem != null)");
                sb.AppendLine($"{inner}        {{");
                sb.AppendLine($"{inner}            var childElem = subItem.WriteToXml(\"{map.TagName}\", {itemNs}, options);");
                sb.AppendLine($"{inner}            element.Add(childElem);");
                sb.AppendLine($"{inner}        }}");
                sb.AppendLine($"{inner}    }}");
                sb.AppendLine($"{inner}}}");
            }
            else
            {
                sb.AppendLine($"{inner}{elsePrefix}if ({valExpr} is global::{map.TypeFullName} item_{i})");
                sb.AppendLine($"{inner}{{");
                sb.AppendLine($"{inner}    var childElem = item_{i}.WriteToXml(\"{map.TagName}\", {itemNs}, options);");
                sb.AppendLine($"{inner}    element.Add(childElem);");
                sb.AppendLine($"{inner}}}");
            }
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void EmitPropertyDeserialize(StringBuilder sb, DFePropertyModel prop)
    {
        var indent = "            ";

        if (prop.PropertyKind == DFePropertyKind.Element)
        {
            if (prop.TypeKind is DFeTypeKind.Class or DFeTypeKind.RootClass or DFeTypeKind.ValueElement)
            {
                sb.AppendLine($"{indent}var elem_{prop.Name} = element.Elements().FirstOrDefault(e => e.Name.LocalName == \"{prop.TagName}\");");
                sb.AppendLine($"{indent}if (elem_{prop.Name} != null)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    this.{prop.Name} = global::{prop.TypeFullName}.ReadFromXml(elem_{prop.Name}, options);");
                sb.AppendLine($"{indent}}}");
                if (prop.Ocorrencia != OcorrenciaModel.Obrigatoria)
                {
                    sb.AppendLine($"{indent}else");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    this.{prop.Name} = null!;");
                    sb.AppendLine($"{indent}}}");
                }
            }
            else
            {
                sb.AppendLine($"{indent}var elem_{prop.Name} = element.Elements().FirstOrDefault(e => e.Name.LocalName == \"{prop.TagName}\");");
                sb.AppendLine($"{indent}if (elem_{prop.Name} != null && !string.IsNullOrEmpty(elem_{prop.Name}.Value))");
                sb.AppendLine($"{indent}{{");
                var parseCall = GetParseCall(prop, $"elem_{prop.Name}.Value");
                sb.AppendLine($"{indent}    this.{prop.Name} = {parseCall};");
                sb.AppendLine($"{indent}}}");
                if (prop.Ocorrencia != OcorrenciaModel.Obrigatoria)
                {
                    sb.AppendLine($"{indent}else");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    this.{prop.Name} = default!;");
                    sb.AppendLine($"{indent}}}");
                }
            }
        }
        else if (prop.PropertyKind == DFePropertyKind.Collection)
        {
            EmitCollectionDeserialize(sb, prop, indent);
        }
        else if (prop.PropertyKind == DFePropertyKind.Dictionary)
        {
            EmitDictionaryDeserialize(sb, prop, indent);
        }
        else if (prop.PropertyKind == DFePropertyKind.Interface)
        {
            EmitInterfaceDeserialize(sb, prop, indent);
        }
    }

    private static void EmitCollectionDeserialize(StringBuilder sb, DFePropertyModel prop, string indent)
    {
        var hasContainer = !string.IsNullOrEmpty(prop.CollectionContainerTagName) &&
                           (prop.ItemMappings.Length > 0 || prop.TagName != prop.CollectionContainerTagName);

        var isArray = prop.TypeFullName.EndsWith("[]");
        var isIEnumerable = prop.TypeFullName.StartsWith("System.Collections.Generic.IEnumerable<") ||
                            prop.TypeFullName.StartsWith("IEnumerable<");

        var itemType = prop.CollectionItemType ?? "object";
        var listVarName = isArray || isIEnumerable ? $"list_{prop.Name}" : $"this.{prop.Name}";

        var searchTarget = "element";
        if (hasContainer)
        {
            sb.AppendLine($"{indent}var container_{prop.Name} = element.Elements().FirstOrDefault(e => e.Name.LocalName == \"{prop.CollectionContainerTagName}\");");
            searchTarget = $"container_{prop.Name}";
        }

        sb.AppendLine($"{indent}if ({searchTarget} != null)");
        sb.AppendLine($"{indent}{{");
        var inner = indent + "    ";

        if (isArray || isIEnumerable)
        {
            sb.AppendLine($"{inner}var {listVarName} = new List<global::{itemType}>();");
        }
        else
        {
            sb.AppendLine($"{inner}if ({listVarName} == null) {listVarName} = new global::{prop.TypeFullName}();");
            sb.AppendLine($"{inner}else {listVarName}.Clear();");
        }

        if (prop.ItemMappings.Length > 0)
        {
            sb.AppendLine($"{inner}foreach (var childNode in {searchTarget}.Elements())");
            sb.AppendLine($"{inner}{{");
            var loopIndent = inner + "    ";
            sb.AppendLine($"{loopIndent}switch (childNode.Name.LocalName)");
            sb.AppendLine($"{loopIndent}{{");

            foreach (var map in prop.ItemMappings)
            {
                sb.AppendLine($"{loopIndent}    case \"{map.TagName}\":");
                sb.AppendLine($"{loopIndent}        {listVarName}?.Add(global::{map.TypeFullName}.ReadFromXml(childNode, options));");
                sb.AppendLine($"{loopIndent}        break;");
            }

            sb.AppendLine($"{loopIndent}}}");
            sb.AppendLine($"{inner}}}");
        }
        else if (prop.CollectionItemTypeKind is DFeTypeKind.Class or DFeTypeKind.RootClass or DFeTypeKind.ValueElement && prop.CollectionItemType != null)
        {
            sb.AppendLine($"{inner}foreach (var childNode in {searchTarget}.Elements().Where(e => e.Name.LocalName == \"{prop.TagName}\"))");
            sb.AppendLine($"{inner}{{");
            sb.AppendLine($"{inner}    var deserializedItem = global::{prop.CollectionItemType}.ReadFromXml(childNode, options);");
            sb.AppendLine($"{inner}    if (deserializedItem != null) {listVarName}?.Add(deserializedItem);");
            sb.AppendLine($"{inner}}}");
        }
        else
        {
            // Primitive collection
            sb.AppendLine($"{inner}foreach (var childNode in {searchTarget}.Elements().Where(e => e.Name.LocalName == \"{prop.TagName}\"))");
            sb.AppendLine($"{inner}{{");
            var parseItemCall = GetPrimitiveOrEnumParseCall(prop, "childNode.Value", itemType);
            sb.AppendLine($"{inner}    {listVarName}?.Add({parseItemCall});");
            sb.AppendLine($"{inner}}}");
        }

        if (isArray)
        {
            sb.AppendLine($"{inner}this.{prop.Name} = {listVarName}.ToArray();");
        }
        else if (isIEnumerable)
        {
            sb.AppendLine($"{inner}this.{prop.Name} = {listVarName};");
        }

        sb.AppendLine($"{indent}}}");
        if (prop.Ocorrencia != OcorrenciaModel.Obrigatoria)
        {
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            if (prop.IsNullable || isArray || isIEnumerable)
            {
                sb.AppendLine($"{indent}    this.{prop.Name} = null!;");
            }
            else
            {
                sb.AppendLine($"{indent}    if (this.{prop.Name} != null) this.{prop.Name}.Clear();");
            }
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void EmitDictionaryDeserialize(StringBuilder sb, DFePropertyModel prop, string indent)
    {
        sb.AppendLine($"{indent}var dictElem_{prop.Name} = element.Elements().FirstOrDefault(e => e.Name.LocalName == \"{prop.TagName}\");");
        sb.AppendLine($"{indent}if (dictElem_{prop.Name} != null)");
        sb.AppendLine($"{indent}{{");
        var inner = indent + "    ";

        var keyName = prop.DictionaryKey?.Name ?? "Key";
        var valName = prop.DictionaryValue?.Name ?? "Value";
        var keyAsAttr = prop.DictionaryKey?.AsAttribute ?? false;
        var keyTipo = prop.DictionaryKey?.Tipo ?? TipoCampoModel.Str;
        var valTipo = prop.DictionaryValue?.Tipo ?? TipoCampoModel.Str;

        var keyType = prop.DictionaryKeyType ?? "string";
        var valType = prop.DictionaryValueType ?? "string";

        sb.AppendLine($"{inner}if (this.{prop.Name} == null) this.{prop.Name} = new global::{prop.TypeFullName}();");
        sb.AppendLine($"{inner}else this.{prop.Name}.Clear();");
        sb.AppendLine($"{inner}foreach (var childNode in dictElem_{prop.Name}.Elements())");
        sb.AppendLine($"{inner}{{");
        var loopIndent = inner + "    ";

        if (keyAsAttr)
        {
            sb.AppendLine($"{loopIndent}var keyAttr = childNode.Attribute(\"{keyName}\");");
            sb.AppendLine($"{loopIndent}if (keyAttr != null)");
            sb.AppendLine($"{loopIndent}{{");
            var parseKey = prop.EnumInfo != null
                ? $"ParseEnum_{GetSafeIdentifier(prop.EnumInfo.EnumFullName)}(keyAttr.Value)"
                : $"DFeSerializerHelper.ParseEnum_Generic<{keyType}>(keyAttr.Value)";
            var parseVal = GetPrimitiveParseCall(valTipo, "childNode.Value", valType);
            sb.AppendLine($"{loopIndent}    var k = {parseKey};");
            sb.AppendLine($"{loopIndent}    var v = {parseVal};");
            sb.AppendLine($"{loopIndent}    this.{prop.Name}[k] = v;");
            sb.AppendLine($"{loopIndent}}}");
        }
        else
        {
            sb.AppendLine($"{loopIndent}var keyNode = childNode.Elements().FirstOrDefault(e => e.Name.LocalName == \"{keyName}\");");
            sb.AppendLine($"{loopIndent}var valNode = childNode.Elements().FirstOrDefault(e => e.Name.LocalName == \"{valName}\");");
            sb.AppendLine($"{loopIndent}if (keyNode != null)");
            sb.AppendLine($"{loopIndent}{{");
            var parseKey = GetPrimitiveParseCall(keyTipo, "keyNode.Value", keyType);
            var parseVal = GetPrimitiveParseCall(valTipo, "valNode?.Value", valType);
            sb.AppendLine($"{loopIndent}    var k = {parseKey};");
            sb.AppendLine($"{loopIndent}    var v = {parseVal};");
            sb.AppendLine($"{loopIndent}    this.{prop.Name}[k] = v;");
            sb.AppendLine($"{loopIndent}}}");
        }

        sb.AppendLine($"{inner}}}");
        sb.AppendLine($"{indent}}}");
        if (prop.Ocorrencia != OcorrenciaModel.Obrigatoria)
        {
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    this.{prop.Name} = null!;");
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void EmitInterfaceDeserialize(StringBuilder sb, DFePropertyModel prop, string indent)
    {
        sb.AppendLine($"{indent}var matched_{prop.Name} = false;");
        sb.AppendLine($"{indent}foreach (var childNode in element.Elements())");
        sb.AppendLine($"{indent}{{");
        var inner = indent + "    ";
        sb.AppendLine($"{inner}switch (childNode.Name.LocalName)");
        sb.AppendLine($"{inner}{{");

        for (int i = 0; i < prop.ItemMappings.Length; i++)
        {
            var map = prop.ItemMappings[i];
            if (map.IsCollection && map.CollectionItemType != null)
            {
                sb.AppendLine($"{inner}    case \"{map.TagName}\":");
                sb.AppendLine($"{inner}        if (this.{prop.Name} is not global::{map.TypeFullName} col_{i})");
                sb.AppendLine($"{inner}        {{");
                sb.AppendLine($"{inner}            col_{i} = new global::{map.TypeFullName}();");
                sb.AppendLine($"{inner}            this.{prop.Name} = col_{i};");
                sb.AppendLine($"{inner}        }}");
                sb.AppendLine($"{inner}        var parsedSub_{i} = global::{map.CollectionItemType}.ReadFromXml(childNode, options);");
                sb.AppendLine($"{inner}        if (parsedSub_{i} != null) col_{i}.Add(parsedSub_{i});");
                sb.AppendLine($"{inner}        matched_{prop.Name} = true;");
                sb.AppendLine($"{inner}        break;");
            }
            else
            {
                sb.AppendLine($"{inner}    case \"{map.TagName}\":");
                sb.AppendLine($"{inner}        this.{prop.Name} = global::{map.TypeFullName}.ReadFromXml(childNode, options);");
                sb.AppendLine($"{inner}        matched_{prop.Name} = true;");
                sb.AppendLine($"{inner}        break;");
            }
        }

        sb.AppendLine($"{inner}}}");
        sb.AppendLine($"{indent}}}");
        if (prop.Ocorrencia != OcorrenciaModel.Obrigatoria)
        {
            sb.AppendLine($"{indent}if (!matched_{prop.Name})");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    this.{prop.Name} = null!;");
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void EmitEnumHelpers(StringBuilder sb, DFeClassModel model)
    {
        var enums = new Dictionary<string, DFeEnumInfoModel>();
        foreach (var prop in model.Properties)
        {
            if (prop.EnumInfo != null && !enums.ContainsKey(prop.EnumInfo.EnumFullName))
            {
                enums[prop.EnumInfo.EnumFullName] = prop.EnumInfo;
            }
        }

        if (enums.Count == 0) return;

        sb.AppendLine("        #region Enum Formatting and Parsing Helpers");
        foreach (var kvp in enums)
        {
            var info = kvp.Value;
            var safeName = GetSafeIdentifier(info.EnumFullName);

            // Formatter
            sb.AppendLine($"        private static string? FormatEnum_{safeName}(global::{info.EnumFullName}? value)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (value == null) return null;");
            sb.AppendLine("            return value switch");
            sb.AppendLine("            {");
            foreach (var member in info.Members)
            {
                sb.AppendLine($"                global::{info.EnumFullName}.{member.MemberName} => \"{member.XmlValue}\",");
            }
            sb.AppendLine("                _ => value.ToString()");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Parser
            sb.AppendLine($"        private static global::{info.EnumFullName} ParseEnum_{safeName}(string? val)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (string.IsNullOrEmpty(val)) return default;");
            sb.AppendLine("            return val switch");
            sb.AppendLine("            {");
            foreach (var member in info.Members)
            {
                sb.AppendLine($"                \"{member.XmlValue}\" => global::{info.EnumFullName}.{member.MemberName},");
            }
            sb.AppendLine($"                _ => Enum.TryParse<global::{info.EnumFullName}>(val, out var parsed) ? parsed : default");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        sb.AppendLine("        #endregion");
    }

    private static string GetFormatCall(DFePropertyModel prop, string valExpr)
    {
        if (prop.EnumInfo != null)
        {
            return $"FormatEnum_{GetSafeIdentifier(prop.EnumInfo.EnumFullName)}({valExpr})";
        }

        var cleanType = prop.TypeFullName.TrimEnd('?');
        if (cleanType == "string")
        {
            if (prop.TipoCampo == TipoCampoModel.StrNumber) return $"DFeSerializerHelper.FormatValue_StrNumber({valExpr}, {prop.Min}, options)";
            if (prop.TipoCampo == TipoCampoModel.StrNumberFill) return $"DFeSerializerHelper.FormatValue_StrNumberFill({valExpr}, {prop.Min}, options)";
            return $"DFeSerializerHelper.FormatValue_Str({valExpr}, {prop.Min}, options)";
        }

        return GetPrimitiveFormatCall(prop.TipoCampo, valExpr, prop.Min);
    }

    private static string GetPrimitiveFormatCall(TipoCampoModel tipo, string valExpr, int min)
    {
        return $"DFeSerializerHelper.FormatValue_{tipo}({valExpr}, {min}, options)";
    }

    private static string GetParseCall(DFePropertyModel prop, string valExpr)
    {
        if (prop.EnumInfo != null)
        {
            return $"ParseEnum_{GetSafeIdentifier(prop.EnumInfo.EnumFullName)}({valExpr})";
        }

        var cleanType = prop.TypeFullName.TrimEnd('?');
        if (cleanType == "string") return $"DFeSerializerHelper.ParseValue_Str({valExpr})";
        if (cleanType == "int") return $"DFeSerializerHelper.ParseValue_Int({valExpr})";
        if (cleanType == "long") return $"DFeSerializerHelper.ParseValue_Long({valExpr})";
        if (cleanType == "decimal") return $"DFeSerializerHelper.ParseValue_De2({valExpr})";
        if (cleanType is "System.DateTime" or "DateTime")
        {
            if (prop.TipoCampo == TipoCampoModel.DatCFe) return $"DFeSerializerHelper.ParseValue_DatCFe({valExpr})";
            if (prop.TipoCampo == TipoCampoModel.Dat) return $"DFeSerializerHelper.ParseValue_Dat({valExpr})";
            if (prop.TipoCampo == TipoCampoModel.HorCFe) return $"DFeSerializerHelper.ParseValue_HorCFe({valExpr})";
            if (prop.TipoCampo == TipoCampoModel.Hor) return $"DFeSerializerHelper.ParseValue_Hor({valExpr})";
            return $"DFeSerializerHelper.ParseValue_DatHor({valExpr})";
        }
        if (cleanType is "System.DateTimeOffset" or "DateTimeOffset") return $"DFeSerializerHelper.ParseValue_DatHorTz({valExpr})";
        if (cleanType == "bool") return $"(bool.TryParse({valExpr}, out var parsedB) ? parsedB : false)";

        return $"DFeSerializerHelper.ParseValue_{prop.TipoCampo}({valExpr})";
    }

    private static string GetPrimitiveOrEnumParseCall(DFePropertyModel prop, string valExpr, string itemType)
    {
        if (prop.EnumInfo != null)
        {
            return $"ParseEnum_{GetSafeIdentifier(prop.EnumInfo.EnumFullName)}({valExpr})";
        }

        var cleanType = itemType.TrimEnd('?');
        if (cleanType == "string") return $"DFeSerializerHelper.ParseValue_Str({valExpr})";
        if (cleanType == "int") return $"DFeSerializerHelper.ParseValue_Int({valExpr})";
        if (cleanType == "long") return $"DFeSerializerHelper.ParseValue_Long({valExpr})";
        if (cleanType == "decimal") return $"DFeSerializerHelper.ParseValue_De2({valExpr})";
        if (cleanType is "System.DateTime" or "DateTime")
        {
            if (prop.TipoCampo == TipoCampoModel.DatCFe) return $"DFeSerializerHelper.ParseValue_DatCFe({valExpr})";
            if (prop.TipoCampo == TipoCampoModel.Dat) return $"DFeSerializerHelper.ParseValue_Dat({valExpr})";
            if (prop.TipoCampo == TipoCampoModel.HorCFe) return $"DFeSerializerHelper.ParseValue_HorCFe({valExpr})";
            if (prop.TipoCampo == TipoCampoModel.Hor) return $"DFeSerializerHelper.ParseValue_Hor({valExpr})";
            return $"DFeSerializerHelper.ParseValue_DatHor({valExpr})";
        }
        if (cleanType is "System.DateTimeOffset" or "DateTimeOffset") return $"DFeSerializerHelper.ParseValue_DatHorTz({valExpr})";
        if (cleanType == "bool") return $"(bool.TryParse({valExpr}, out var parsedB) ? parsedB : false)";

        return $"DFeSerializerHelper.ParseValue_{prop.TipoCampo}({valExpr})";
    }

    private static string GetPrimitiveParseCall(TipoCampoModel tipo, string valExpr, string targetType)
    {
        var cleanType = targetType.TrimEnd('?');
        if (cleanType == "string") return $"DFeSerializerHelper.ParseValue_Str({valExpr})";
        if (cleanType == "int") return $"DFeSerializerHelper.ParseValue_Int({valExpr})";
        if (cleanType == "long") return $"DFeSerializerHelper.ParseValue_Long({valExpr})";
        if (cleanType == "decimal") return $"DFeSerializerHelper.ParseValue_De2({valExpr})";
        return $"({targetType})DFeSerializerHelper.ParseValue_{tipo}({valExpr})";
    }

    public static string GetSafeIdentifier(string name)
    {
        return name.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace("`", "_").Replace("?", "");
    }
}
